services:
  asir_dns:
    container_name: asir_dns
    image: ubuntu/bind9:latest
    # usamos esta imagen para poder ver los logs
    # la imagen de internetsystemsconsortium/bind9
    # no muestra los logs
    ports:
      - 53:53
    networks:
      dns_subnet:
        ipv4_address: 172.28.5.1
    volumes:
      - ./conf:/etc/bind
      - ./zonas:/var/lib/bind
networks:
  dns_subnet:
    external: true
